services:
  postgres:
    image: postgres
    volumes:
      - ./karyakram:/var/lib/postgresql/data
    # pass username and password to postgres from .env file
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    # port mapping with postgres container with host machine
    ports:
      - 5432:5432
    networks:
      - karyakram-network

networks:
  karyakram-network:
    driver: bridge
